//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int id { get; set; }
        public int userid { get; set; }
        public double salary { get; set; }
        public int service_id { get; set; }
        public string work_area { get; set; }
        public string work_status { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
