//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.Employees = new HashSet<Employee>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string details { get; set; }
        public double price { get; set; }
        public string status { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
