//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.AssignedProjects = new HashSet<AssignedProject>();
        }
    
        public int id { get; set; }
        public string projectName { get; set; }
        public string description { get; set; }
        public System.DateTime createdDate { get; set; }
        public int creatorId { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> completedDate { get; set; }
    
        public virtual ICollection<AssignedProject> AssignedProjects { get; set; }
        public virtual User User { get; set; }
    }
}
