//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AssignedProjects = new HashSet<AssignedProject>();
            this.Projects = new HashSet<Project>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string userType { get; set; }
    
        public virtual ICollection<AssignedProject> AssignedProjects { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
